version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: lara_two_app
        container_name: app_two
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
        depends_on:
            - db_two

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver_two
        restart: unless-stopped
        tty: true
        ports:
            - "81:80"
            - "444:443"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db_two:
        image: mysql:8.0
        container_name: db_two
        restart: unless-stopped
        tty: true
        ports:
            - "3309:3306"
        environment:
            MYSQL_DATABASE: future_database
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
